# Generated by Django 3.1.6 on 2023-05-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_image/')),
                ('posted_date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
