# Generated by Django 3.1.6 on 2023-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_advertises'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrackGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('release_date', models.DateField(null=True)),
                ('crack_date', models.DateField(null=True)),
                ('drm', models.CharField(max_length=40)),
                ('scene_grp', models.CharField(max_length=40)),
                ('c_game_image', models.ImageField(blank=True, null=True, upload_to='c_game_image/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
