# Generated by Django 3.1.6 on 2023-05-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_crackgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crackgame',
            name='drm',
        ),
        migrations.RemoveField(
            model_name='crackgame',
            name='scene_grp',
        ),
    ]
