# Generated by Django 3.1.6 on 2023-05-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20230513_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crackgame',
            name='crack_date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='crackgame',
            name='release_date',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
