# Generated by Django 3.1.6 on 2023-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_useradvertises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradvertises',
            name='adv_image',
        ),
        migrations.AddField(
            model_name='useradvertises',
            name='u_adv_image',
            field=models.ImageField(blank=True, null=True, upload_to='u_adv_image/'),
        ),
    ]
