# Generated by Django 3.1.6 on 2023-05-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20230530_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradvertises',
            name='customerId',
        ),
        migrations.AddField(
            model_name='useradvertises',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.customer'),
        ),
    ]
